App/Entities/Student.cs
namespace App.Entities
{
    public class Student
    {
        public int Id { get; set; }
        
        public string Name { get; set; }       
        
    }
}

App/ViewModels/AddStudentViewModel.cs
namespace App.ViewModels
{
    public class AddStudentViewModel
    {
        
    }
}

App/ViewModels/EditStudentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace App.ViewModels
{
    public class EditStudentViewModel
    {
        public int Id { get; set; }
        
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "You have to enter a first name!")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "You have to enter a last name!")]
        public string LastName { get; set; }

        [Display(Name = "E-mail")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "You have to enter an e-mail!")]
        public string Email { get; set; }

        [Display(Name = "Phone")]
        [RegularExpression(@"[0-9]{9,10}", ErrorMessage = "Only Digits. Min 9 - Max 10")]
        [Required(ErrorMessage = "You have to enter your phone number!")]
        public string Phone { get; set; }

        [Display(Name = "Street Adress")]
        [Required(ErrorMessage = "Please fill out your adress.")]
        public string Adress { get; set; }
    }
}

App/Controllers/BuyCoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Interfaces;
using App.Models;
using App.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class BuyCoursesController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IStudentService _studentService;

        public BuyCoursesController(ICourseService courseService, IStudentService studentService)
        {
            _courseService = courseService;
            _studentService = studentService;
        }

        [HttpGet()]
        public async Task<IActionResult> Index(string studentEmail)
        {
            var student = await _studentService.GetStudentByEmailAsync(studentEmail);
            if (studentEmail != null)
            {
                var model = new DetailStudentCourseViewModel
                {
                    StudentId = student.StudentId,
                    FirstName = student.FirstName,
                    LastName = student.LastName,
                    Email = student.Email,
                    Phone = student.Phone,
                    Adress = student.Adress,
                    Courses = student.Courses,
                    AvailableCourses = new List<CourseModel>()
                };

                var courses = await _courseService.GetActiveCoursesAsync();
                foreach (var c in courses)
                {
                    if (!IsCourseAvailable(model.Courses, c))
                    {
                        model.AvailableCourses.Add(c);
                    }
                }

                return View("Index", model);
            }
            return Content("Email not found!");
        }

        [HttpGet()]
        public async Task<IActionResult> AddCourseToStudent(int studentId, int courseId)
        {
            var course = await _courseService.GetCourseByIdAsync(courseId);
            var student = await _studentService.GetStudentByIdAsync(studentId);

            if (student != null && course != null)
            {
                var model = new BuyNewCourseViewModel()
                {
                    CourseId = course.CourseId,
                    CourseNumber = course.CourseNumber,
                    Title = course.Title,
                    Description = course.Description,
                    Length = course.Length,
                    Price = course.Price,
                    StudentId = student.StudentId,
                    FirstName = student.FirstName,
                    LastName = student.LastName
                };
                return View("AddCourseToStudent", model);
            }
            return Content($"Could not find studentID {studentId} or courseID {courseId}");
        }

        [HttpPost()]
        public async Task<IActionResult> AddCourseToStudent(int studentId, int courseId, BuyNewCourseViewModel data)
        {
            // if(!ModelState.IsValid) return View("AddCourseToStudent", data);

            var course = await _courseService.GetCourseByIdAsync(courseId);
            var student = await _studentService.GetStudentByIdAsync(studentId);

            if (course != null && student != null)
            {
                var courseStudent = new CourseStudentModel
                {
                    StudentId = student.StudentId,
                    CourseId = course.CourseId
                };

                try
                {
                    if (await _studentService.AddCourseToStudentAsync(student.StudentId, course.CourseId, courseStudent))
                        return RedirectToAction("Index", "Students");
                }
                catch (Exception ex)
                {
                    return View("Error", ex.Message);
                }
            }
            return Content($"Did not find student {studentId} or course {courseId}");
        }

        private bool IsCourseAvailable(ICollection<CourseModel> studentCourseList, CourseModel course)
        {
            bool hasBought = false;
            foreach (var c in studentCourseList)
            {
                if (c.CourseId == course.CourseId)
                {
                    hasBought = true;
                    break;
                }
            }

            return hasBought;
        }
    }
}

App/Controllers/StudentsController.cs
using System;
using System.Threading.Tasks;
using App.Interfaces;
using App.Models;
using App.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentService _service;

        public StudentsController(IStudentService service)
        {
            _service = service;
        }

        [HttpGet()]
        public async Task<IActionResult> Index()
        {
            var result = await _service.GetStudentsAsync();
            return View("Index", result);
        }

        [HttpGet()]
        public IActionResult AddStudent()
        {
            return View("AddStudent");
        }

        [HttpPost]
        public async Task<IActionResult> AddStudent(AddStudentViewModel data)
        {
            if (!ModelState.IsValid)
            {
                return View("AddStudent", data);
            }

            var student = new StudentModel
            {
                FirstName = data.FirstName,
                LastName = data.LastName,
                Email = data.Email,
                Phone = data.Phone,
                Adress = data.Adress
            };

            try
            {
                if (await _service.AddStudent(student))
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Error");
        }

        public async Task<IActionResult> DeleteStudent(int id)
        {
            var student = await _service.GetStudentByIdAsync(id);
            if(await _service.DeleteStudent(student.StudentId)) return RedirectToAction("Index");
            return View("Error");
        }
        [HttpGet()]
        public async Task<IActionResult> EditStudent(int id)
        {
            var student = await _service.GetStudentByIdAsync(id);

            var model = new EditStudentViewModel
            {
                Id = student.StudentId,
                FirstName = student.FirstName,
                LastName = student.LastName,
                Email = student.Email,
                Phone = student.Phone,
                Adress = student.Adress
            };

            return View("EditStudent", model);
        }

        [HttpPost()]
        public async Task<IActionResult> EditStudent(EditStudentViewModel data)
        {
            if(!ModelState.IsValid)
            {
                return View("EditStudent", data);
            }

            var student = await _service.GetStudentByIdAsync(data.Id);

            student.FirstName = data.FirstName;
            student.LastName = data.LastName;
            student.Email = data.Email;
            student.Phone = data.Phone;
            student.Adress = data.Adress;

            try
            {
                if(await _service.EditStudent(student.StudentId, student)) return RedirectToAction("Index");                
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Error");
        }
    }
}

App/Views/Students/AddStudent.cshtml
@model App.ViewModels.AddStudentViewModel

<h1>Here you can add a new student </h1>


@* Creating a form for adding course *@

<form asp-controller="Students" asp-action="AddStudent" method="POST">
    <div class="card">
        <div class="card-header">
            <h4>Add new student</h4>
        </div>
        <div class="p-3">
            <div class="mb-3">
                <label class="form-label" asp-for="FirstName"></label>
                <input class="form-control" asp-for="FirstName">
                <span asp-validation-for="FirstName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="LastName"></label>
                <input class="form-control" asp-for="LastName">
                <span asp-validation-for="LastName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Email"></label>
                <input class="form-control" asp-for="Email">
                <span asp-validation-for="Email"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Phone"></label>
                <input class="form-control" asp-for="Phone">
                <span asp-validation-for="Phone"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Adress"></label>
                <input class="form-control" asp-for="Adress">
                <span asp-validation-for="Adress"></span>
            </div>
            <input class="btn btn-primary" type="submit" value="Save">
        </div>
    </div>
</form>

App/Views/Students/EditStudent.cshtml
@model App.ViewModels.EditStudentViewModel

<h1>Edit the student details </h1>


@* Creating a form for adding course *@

<form asp-controller="Students" asp-action="EditStudent" method="POST">
    <div class="card">
        <div class="card-header">
            <h4>Edit details</h4>
        </div>
        <div class="p-3">
            <div class="mb-3">
                <label class="form-label" asp-for="FirstName"></label>
                <input class="form-control" asp-for="FirstName">
                <span asp-validation-for="FirstName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="LastName"></label>
                <input class="form-control" asp-for="LastName">
                <span asp-validation-for="LastName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Email"></label>
                <input class="form-control" asp-for="Email">
                <span asp-validation-for="Email"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Phone"></label>
                <input class="form-control" asp-for="Phone">
                <span asp-validation-for="Phone"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Adress"></label>
                <input class="form-control" asp-for="Adress">
                <span asp-validation-for="Adress"></span>
            </div>
            <input class="btn btn-primary" type="submit" value="Save">
        </div>
    </div>
</form>

App/Views/Students/Index.cshtml
@{
  ViewData["Title"] = "Student List";
}
@model IEnumerable<App.Models.StudentModel>

<a class="btn btn-primary mb-3" asp-action="AddStudent">Add Student</a>
<h2>Student List</h2>

<table class="table">
  <thead>
    <tr class="table-primary">
      <th></th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Adress</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var student in Model)
    {
      <tr>
        <td style="text-align:center;">
          <a asp-action="EditStudent" asp-route-id="@student.StudentId" class="btn btn-primary btn-sm">Edit</a>
        </td>
        <td>@student.FirstName</td>
        <td>@student.LastName</td>
        <td>@student.Email</td>
        <td>@student.Phone</td>
        <td>@student.Adress</td>
        <td style="text-align: center;">
          <a asp-action="DeleteStudent" asp-route-Id="@student.StudentId" class="btn btn-primary btn-sm">Delete</a>
        </td>
        <td>
          <a asp-controller="BuyCourses" asp-action="Index" asp-route-studentEmail="@student.Email" class="btn btn-primary btn-sm">Buy Courses</a>
        </td>
      </tr>
    }
  </tbody>
</table>