App/Controllers/CoursesController.cs
using App.Entities;
using App.Interfaces;
using App.Models;
using App.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;


namespace App.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICourseService _service;

        public CoursesController(IUnitOfWork unitOfWork, ICourseService service)
        {
            _service = service;
        }

        //GET /Courses/
        [HttpGet()]
        public async Task<IActionResult> Index()
        {
            var result = await _service.GetCoursesAsync();
            return View("Index", result);
        }

        [HttpGet()]
        public async Task<IActionResult> AddCourse()
        {        
        //     var levels = await _service.GetLevelsAsync();        
        //     var courseModel = new AddCourseViewModel();
        //     courseModel.LevelCollection = levels;     
            return View("AddCourse");
        }

        [HttpPost()]
        public async Task<IActionResult> AddCourse(AddCourseViewModel data)
        {
            if (!ModelState.IsValid)
            {
                return View("AddCourse", data);
            }

            var course = new CourseModel
            {
                Title = data.Title,
                CourseNumber = data.CourseNumber,
                Description = data.Description,
                Level = data.Level,
                Length = data.Length,
                Price = (decimal)data.Price
            };

            try
            {
                if (await _service.AddCourse(course))
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Error");
        }

        //Method for getting the course to Edit
        [HttpGet()]
        public async Task<IActionResult> EditCourse(int id)
        {
            var course = await _service.GetCourseByIdAsync(id);

            var model = new EditCourseViewModel
            {
                Id = course.CourseId,
                CourseNumber = course.CourseNumber,
                Title = course.Title,
                Description = course.Description,
                Length = course.Length,
                Level = course.Level,
                Price = course.Price
            };

            return View("EditCourse", model);
        }

        //Method for updating the course with new parameters, saves to Database
        [HttpPost()]
        public async Task<IActionResult> EditCourse(EditCourseViewModel data)
        {
            if (!ModelState.IsValid)
            {
                return View("EditCourse", data);
            }

            var course = await _service.GetCourseByIdAsync(data.Id);

            course.Title = data.Title;
            course.Description = data.Description;
            course.Length = data.Length;
            course.Level = data.Level;
            course.Price = data.Price;

            try
            {
                if (await _service.EditCourse(course.CourseId, course)) return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Error");
        }

        public async Task<IActionResult> Delete(int courseNumber)
        {
            var course = await _service.GetCourseByCourseNoAsync(courseNumber);

            if (await _service.DeleteCourse(course.CourseNumber)) return RedirectToAction("Index");
            return View("Error");
        }
    }
}

App/Controllers/StudentsController.cs
using System;
using System.Threading.Tasks;
using App.Interfaces;
using App.Models;
using App.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentService _service;

        public StudentsController(IStudentService service)
        {
            _service = service;
        }

        [HttpGet()]
        public async Task<IActionResult> Index()
        {
            var result = await _service.GetStudentsAsync();
            return View("Index", result);
        }

        [HttpGet()]
        public IActionResult AddStudent()
        {
            return View("AddStudent");
        }

        [HttpPost]
        public async Task<IActionResult> AddStudent(AddStudentViewModel data)
        {
            if (!ModelState.IsValid)
            {
                return View("AddStudent", data);
            }

            var student = new StudentModel
            {
                FirstName = data.FirstName,
                LastName = data.LastName,
                Email = data.Email,
                Phone = data.Phone,
                Adress = data.Adress
            };

            try
            {
                if (await _service.AddStudent(student))
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Error");
        }

        public async Task<IActionResult> DeleteStudent(int id)
        {
            var student = await _service.GetStudentByIdAsync(id);
            if(await _service.DeleteStudent(student.StudentId)) return RedirectToAction("Index");
            return View("Error");
        }
        [HttpGet()]
        public async Task<IActionResult> EditStudent(int id)
        {
            var student = await _service.GetStudentByIdAsync(id);

            var model = new EditStudentViewModel
            {
                Id = student.StudentId,
                FirstName = student.FirstName,
                LastName = student.LastName,
                Email = student.Email,
                Phone = student.Phone,
                Adress = student.Adress
            };

            return View("EditStudent", model);
        }

        [HttpPost()]
        public async Task<IActionResult> EditStudent(EditStudentViewModel data)
        {
            if(!ModelState.IsValid)
            {
                return View("EditStudent", data);
            }

            var student = await _service.GetStudentByIdAsync(data.Id);

            student.FirstName = data.FirstName;
            student.LastName = data.LastName;
            student.Email = data.Email;
            student.Phone = data.Phone;
            student.Adress = data.Adress;

            try
            {
                if(await _service.EditStudent(student.StudentId, student)) return RedirectToAction("Index");                
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Error");
        }
    }
}

App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Westcoast Education</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses"
                                asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students"
                                asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

App/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <article>
            <section>
                <section>
                    @RenderSection("topSection", false)
                </section>
                @RenderBody()
            </section>
        </article>
    </main>
    
</body>
</html>